// 2026 Nagoya-Aichi Asian Games — event schedule dataset
// Source: user-provided planning sheet (dates, venues, addresses, map links)
// hkg: true = Hong Kong delegation confirmed competing in this sport
// (re-verified against the full "20th Asian Games Delegation Athletes" roster file —
//  supersedes the earlier keyword-based hkg guess; see CHANGED FLAGS note below)
// disciplineKey: links a row to its athlete roster in ROSTER (null = no confirmed HKG roster)
const EVENTS = [
  { sport:"開閉幕禮", event:"開幕禮", start:"2026-09-19", end:"2026-09-19", venue:"名古屋市瑞穗公園陸上競技場", city:"名古屋市", address:"愛知県名古屋市瑞穂区山下通5-1", mapQuery:"名古屋市瑞穂公園陸上競技場", disciplineKey:null, hkg:false },
  { sport:"開閉幕禮", event:"閉幕禮", start:"2026-10-04", end:"2026-10-04", venue:"名古屋市瑞穗公園陸上競技場", city:"名古屋市", address:"愛知県名古屋市瑞穂区山下通5-1", mapQuery:"名古屋市瑞穂公園陸上競技場", disciplineKey:null, hkg:false },
  { sport:"水上運動", event:"游泳", start:"2026-09-20", end:"2026-09-25", venue:"東京水上運動中心", city:"東京都", address:"東京都江東区辰巳2-2-1", mapQuery:"東京アクアティクスセンター", disciplineKey:"aquatics_swimming", hkg:true },
  { sport:"水上運動", event:"跳水", start:"2026-09-26", end:"2026-09-30", venue:"東京水上運動中心", city:"東京都", address:"東京都江東区辰巳2-2-1", mapQuery:"東京アクアティクスセンター", disciplineKey:"aquatics_diving", hkg:true },
  { sport:"水上運動", event:"韻律泳/花樣游泳", start:"2026-09-26", end:"2026-09-28", venue:"濱松市古橋廣之進紀念水泳場", city:"濱松市", address:"静岡県浜松市西区篠原町23982-1", mapQuery:"浜松市古橋廣之進記念水泳場", disciplineKey:"aquatics_artisticswimming", hkg:true },
  { sport:"水上運動", event:"水球", start:"2026-09-20", end:"2026-10-03", venue:"名古屋市綜合體育館 (Rainbow Pool)", city:"名古屋市", address:"愛知県名古屋市南区東又兵ヱ町5-1-16", mapQuery:"日本ガイシアリーナ", disciplineKey:"aquatics_water_polo", hkg:true },
  { sport:"射箭", event:"反曲弓、複合弓", start:"2026-09-26", end:"2026-10-03", venue:"岡崎中央綜合公園 多目的廣場", city:"岡崎市", address:"愛知県岡崎市高隆寺町字峠1", mapQuery:"岡崎中央総合公園 多目的広場", disciplineKey:"archery", hkg:true },
  { sport:"田徑", event:"田徑", start:"2026-09-24", end:"2026-09-29", venue:"名古屋市瑞穗公園陸上競技場", city:"名古屋市", address:"愛知県名古屋市瑞穂区山下通5-1", mapQuery:"名古屋市瑞穂公園陸上競技場", disciplineKey:"athletics", hkg:true },
  { sport:"田徑", event:"馬拉松", start:"2026-09-26", end:"2026-09-26", venue:"名古屋市瑞穗公園陸上競技場", city:"名古屋市", address:"愛知県名古屋市瑞穂区山下通5-1", mapQuery:"名古屋市瑞穂公園陸上競技場", disciplineKey:"athletics", hkg:true },
  { sport:"田徑", event:"競走", start:"2026-09-23", end:"2026-09-27", venue:"愛知縣廳及名古屋市役所周邊", city:"名古屋市", address:"愛知県名古屋市中区三の丸", mapQuery:"愛知県庁", disciplineKey:"athletics", hkg:true },
  { sport:"羽毛球", event:"男/女團體、各單項", start:"2026-09-20", end:"2026-09-29", venue:"一宮市綜合體育館", city:"一宮市", address:"愛知県一宮市光明寺字白山前20", mapQuery:"一宮市総合体育館", disciplineKey:"badminton", hkg:true },
  { sport:"棒球", event:"棒球", start:"2026-09-21", end:"2026-09-27", venue:"岡崎中央綜合公園棒球場", city:"岡崎市", address:"愛知県岡崎市高隆寺町字峠1", mapQuery:"岡崎市民球場", disciplineKey:"baseball", hkg:true },
  { sport:"棒球", event:"棒球", start:"2026-09-21", end:"2026-09-27", venue:"豐橋市民球場", city:"豐橋市", address:"愛知県豊橋市岩田町1-2", mapQuery:"豊橋市民球場", disciplineKey:"baseball", hkg:true },
  { sport:"壘球", event:"壘球", start:"2026-09-26", end:"2026-10-03", venue:"安城市壘球場", city:"安城市", address:"愛知県安城市新田町新定41", mapQuery:"安城市ソフトボール場", disciplineKey:"softball", hkg:true },
  { sport:"籃球", event:"五人制籃球", start:"2026-09-10", end:"2026-09-26", venue:"愛知國際體育館 (IG Arena)", city:"名古屋市", address:"愛知県名古屋市北区名城1-4-1", mapQuery:"愛知国際アリーナ", disciplineKey:"basketball_5x5", hkg:true },
  { sport:"籃球", event:"三人制籃球", start:"2026-09-21", end:"2026-09-25", venue:"金城埠頭車站站前廣場", city:"名古屋市", address:"愛知県名古屋市港区金城ふ頭3丁目", mapQuery:"金城ふ頭駅前広場", disciplineKey:"basketball_3x3", hkg:true },
  { sport:"拳擊", event:"拳擊", start:"2026-09-21", end:"2026-10-02", venue:"西尾市綜合體育館", city:"西尾市", address:"愛知県西尾市小島町大郷1-1", mapQuery:"西尾市総合体育館", disciplineKey:null, hkg:false },
  { sport:"體育舞蹈", event:"霹靂舞", start:"2026-10-02", end:"2026-10-03", venue:"Aichi Sky Expo (愛知天空展覽館)", city:"常滑市", address:"愛知県常滑市セントレア5-10-1", mapQuery:"Aichi Sky Expo", disciplineKey:"dancesport_breaking", hkg:true },
  { sport:"獨木舟", event:"靜水競速", start:"2026-09-23", end:"2026-09-26", venue:"三好湖獨木舟競技場", city:"三好市", address:"愛知県みよし市三好町池ノ原", mapQuery:"保田ヶ池カヌー競技場", disciplineKey:"canoe_sprint", hkg:true },
  { sport:"獨木舟", event:"激流迴旋", start:"2026-09-29", end:"2026-10-02", venue:"矢作川獨木舟激流迴旋競技場", city:"豐田市", address:"愛知県豊田市（矢作川）", mapQuery:"矢作川カヌースラロームコース", disciplineKey:null, hkg:false },
  { sport:"武術/格鬥", event:"柔術", start:"2026-10-01", end:"2026-10-03", venue:"愛知縣武道館", city:"名古屋市", address:"愛知県名古屋市港区丸池町1-1-4", mapQuery:"愛知県武道館", disciplineKey:null, hkg:false },
  { sport:"武術/格鬥", event:"克柔術", start:"2026-09-27", end:"2026-09-29", venue:"愛知縣武道館", city:"名古屋市", address:"愛知県名古屋市港区丸池町1-1-4", mapQuery:"愛知県武道館", disciplineKey:null, hkg:false },
  { sport:"武術/格鬥", event:"綜合格鬥", start:"2026-09-20", end:"2026-09-22", venue:"名古屋市稻永體育中心", city:"名古屋市", address:"愛知県名古屋市港区野跡5-1-10", mapQuery:"名古屋市稲永スポーツセンター", disciplineKey:null, hkg:false },
  { sport:"板球", event:"T20 板球", start:"2026-09-17", end:"2026-10-03", venue:"蟋蟀田徑場 (Korogi Athletic Park)", city:"豐田市", address:"愛知県豊田市", mapQuery:"Korogi Athletic Park", disciplineKey:"cricket", hkg:true },
  { sport:"單車", event:"場地單車", start:"2026-09-29", end:"2026-10-02", venue:"伊豆室內單車館", city:"伊豆市", address:"静岡県伊豆市大野1826", mapQuery:"伊豆ベロドローム", disciplineKey:"cycling_track_road", hkg:true },
  { sport:"單車", event:"公路單車", start:"2026-09-20", end:"2026-09-23", venue:"新城市公路單車賽道", city:"新城市", address:"愛知県新城市", mapQuery:"新城市", disciplineKey:"cycling_track_road", hkg:true },
  { sport:"單車", event:"越野單車", start:"2026-09-24", end:"2026-09-25", venue:"小幡綠地公園", city:"名古屋市", address:"愛知県名古屋市守山区牛牧", mapQuery:"小幡緑地", disciplineKey:"cycling_mountainbike", hkg:true },
  { sport:"單車", event:"小輪車競速", start:"2026-09-28", end:"2026-09-28", venue:"名古屋單車館 BMX 賽道", city:"名古屋市", address:"愛知県名古屋市", mapQuery:"名古屋競輪場BMXコース", disciplineKey:"cycling_bmx_racing", hkg:true },
  { sport:"單車", event:"小輪車花式", start:"2026-09-26", end:"2026-09-27", venue:"Aichi Sky Expo (愛知天空展覽館)", city:"常滑市", address:"愛知県常滑市セントレア5-10-1", mapQuery:"Aichi Sky Expo", disciplineKey:null, hkg:false },
  { sport:"馬術", event:"馬術各項", start:"2026-09-21", end:"2026-10-04", venue:"馬術公園 (Equestrian Park)", city:"東京/愛知", address:"東京都世田谷区上用賀2-1-1", mapQuery:"馬事公苑", disciplineKey:"equestrian", hkg:true },
  { sport:"電競", event:"電子競技", start:"2026-09-23", end:"2026-10-02", venue:"Aichi Sky Expo (愛知天空展覽館)", city:"常滑市", address:"愛知県常滑市セントレア5-10-1", mapQuery:"Aichi Sky Expo", disciplineKey:"esports", hkg:true },
  { sport:"劍擊", event:"花劍、重劍、佩劍", start:"2026-09-22", end:"2026-09-27", venue:"Aichi Sky Expo (愛知天空展覽館)", city:"常滑市", address:"愛知県常滑市セントレア5-10-1", mapQuery:"Aichi Sky Expo", disciplineKey:"fencing", hkg:true },
  { sport:"足球", event:"足球", start:"2026-09-14", end:"2026-10-03", venue:"豐田體育場", city:"豐田市", address:"愛知県豊田市千石町7-2", mapQuery:"豊田スタジアム", disciplineKey:"football", hkg:true },
  { sport:"足球", event:"足球", start:"2026-09-14", end:"2026-10-03", venue:"長居體育場 (Yanmar Stadium)", city:"大阪市", address:"大阪府大阪市東住吉区長居公園1-1", mapQuery:"ヤンマースタジアム長居", disciplineKey:"football", hkg:true },
  { sport:"足球", event:"足球", start:"2026-09-14", end:"2026-10-03", venue:"名古屋市港足球場", city:"名古屋市", address:"愛知県名古屋市港区野跡4-11-12", mapQuery:"名古屋市港サッカー場", disciplineKey:"football", hkg:true },
  { sport:"足球", event:"足球", start:"2026-09-14", end:"2026-10-03", venue:"WAVE STADIUM 刈谷", city:"刈谷市", address:"愛知県刈谷市築地町荒田1", mapQuery:"ウェーブスタジアム刈谷", disciplineKey:"football", hkg:true },
  { sport:"足球", event:"足球", start:"2026-09-14", end:"2026-10-03", venue:"岐阜長良川競技場", city:"岐阜市", address:"岐阜県岐阜市大野2675-28", mapQuery:"長良川競技場", disciplineKey:"football", hkg:true },
  { sport:"足球", event:"足球", start:"2026-09-14", end:"2026-10-03", venue:"靜岡縣小笠山綜合體育場 (Ecopa)", city:"袋井市", address:"静岡県袋井市愛野2300-1", mapQuery:"エコパスタジアム", disciplineKey:"football", hkg:true },
  { sport:"高爾夫", event:"高爾夫", start:"2026-09-30", end:"2026-10-03", venue:"春日井鄉村俱樂部 東場", city:"春日井市", address:"愛知県春日井市牛山町1630", mapQuery:"春日井カントリークラブ", disciplineKey:"golf", hkg:true },
  { sport:"體操", event:"競技體操", start:"2026-09-21", end:"2026-09-25", venue:"名古屋市綜合體育館 (Rainbow Hall)", city:"名古屋市", address:"愛知県名古屋市南区東又兵ヱ町5-1-16", mapQuery:"日本ガイシホール", disciplineKey:"gymnastics_artistic", hkg:true },
  { sport:"體操", event:"藝術體操/韻律體操", start:"2026-10-01", end:"2026-10-03", venue:"名古屋市綜合體育館 (Rainbow Hall)", city:"名古屋市", address:"愛知県名古屋市南区東又兵ヱ町5-1-16", mapQuery:"日本ガイシホール", disciplineKey:"gymnastics_rhythmic", hkg:true },
  { sport:"體操", event:"彈床", start:"2026-09-27", end:"2026-09-27", venue:"名古屋市綜合體育館 (Rainbow Hall)", city:"名古屋市", address:"愛知県名古屋市南区東又兵ヱ町5-1-16", mapQuery:"日本ガイシホール", disciplineKey:"gymnastics_trampoline", hkg:true },
  { sport:"手球", event:"手球", start:"2026-09-20", end:"2026-10-02", venue:"春日井市綜合體育館", city:"春日井市", address:"愛知県春日井市鷹来町4196-3", mapQuery:"春日井市総合体育館", disciplineKey:"handball", hkg:true },
  { sport:"手球", event:"手球", start:"2026-09-20", end:"2026-10-02", venue:"豐田合成競技場 (ENTRIO)", city:"稻澤市", address:"愛知県稲沢市下津北山1丁目16-4", mapQuery:"豊田合成記念体育館エントリオ", disciplineKey:"handball", hkg:true },
  { sport:"曲棍球", event:"曲棍球", start:"2026-09-18", end:"2026-10-03", venue:"岐阜縣綠色體育場", city:"各務原市", address:"岐阜県各務原市下切町6-1-4", mapQuery:"岐阜県グリーンスタジアム", disciplineKey:null, hkg:false },
  { sport:"柔道", event:"柔道", start:"2026-09-30", end:"2026-10-03", venue:"愛知國際體育館 (IG Arena)", city:"名古屋市", address:"愛知県名古屋市北区名城1-4-1", mapQuery:"愛知国際アリーナ", disciplineKey:"judo", hkg:true },
  { sport:"卡巴迪", event:"卡巴迪", start:"2026-09-21", end:"2026-09-26", venue:"東海市民體育館", city:"東海市", address:"愛知県東海市高横須賀町桝穴1-1", mapQuery:"東海市民体育館", disciplineKey:null, hkg:false },
  { sport:"空手道", event:"競賽、型", start:"2026-09-20", end:"2026-09-23", venue:"豐橋市綜合體育館", city:"豐橋市", address:"愛知県豊橋市神野新田町メノ割1-3", mapQuery:"豊橋市総合体育館", disciplineKey:"karate", hkg:true },
  { sport:"現代五項", event:"現代五項", start:"2026-09-16", end:"2026-09-20", venue:"安城市體育公園", city:"安城市", address:"愛知県安城市新田町新定41", mapQuery:"安城市体育館", disciplineKey:"modern_pentathlon", hkg:true },
  { sport:"賽艇", event:"賽艇", start:"2026-09-20", end:"2026-09-24", venue:"長良川國際賽艇場", city:"海津市", address:"岐阜県海津市海津町", mapQuery:"長良川国際レガッタコース", disciplineKey:"rowing", hkg:true },
  { sport:"七人欖球", event:"七人欖球", start:"2026-10-01", end:"2026-10-03", venue:"名古屋市瑞穗公園欖球場", city:"名古屋市", address:"愛知県名古屋市瑞穂区山下通5-1", mapQuery:"名古屋市瑞穂公園ラグビー場", disciplineKey:"rugby_sevens", hkg:true },
  { sport:"帆船", event:"帆船", start:"2026-09-26", end:"2026-10-03", venue:"海陽遊艇港", city:"蒲郡市", address:"愛知県蒲郡市海陽町1-7", mapQuery:"海陽ヨットハーバー", disciplineKey:"sailing", hkg:true },
  { sport:"藤球", event:"藤球", start:"2026-09-20", end:"2026-10-03", venue:"名古屋市瑞穗公園體育館", city:"名古屋市", address:"愛知県名古屋市瑞穂区田辺通3-4", mapQuery:"名古屋市瑞穂公園体育館", disciplineKey:null, hkg:false },
  { sport:"射擊", event:"步槍、手槍、飛碟", start:"2026-09-20", end:"2026-10-01", venue:"愛知縣綜合射擊場", city:"豐田市", address:"愛知県豊田市西丹波町平五郎82-2", mapQuery:"愛知県総合射撃場", disciplineKey:"shooting", hkg:true },
  { sport:"滑板", event:"街式、公園賽", start:"2026-09-24", end:"2026-09-27", venue:"Aichi Sky Expo (愛知天空展覽館)", city:"常滑市", address:"愛知県常滑市セントレア5-10-1", mapQuery:"Aichi Sky Expo", disciplineKey:"roller_skateboarding", hkg:true },
  { sport:"運動攀登", event:"攀岩、抱石賽、難度賽", start:"2026-09-29", end:"2026-10-03", venue:"港區國際展覽中心 (Portmesse)", city:"名古屋市", address:"愛知県名古屋市港区金城ふ頭2-2", mapQuery:"ポートメッセなごや", disciplineKey:"sport_climbing", hkg:true },
  { sport:"壁球", event:"壁球", start:"2026-09-23", end:"2026-10-02", venue:"名古屋金城埠頭競技場", city:"名古屋市", address:"愛知県名古屋市港区金城ふ頭2-7-1", mapQuery:"武田テバオーシャンアリーナ", disciplineKey:"squash", hkg:true },
  { sport:"衝浪", event:"衝浪", start:"2026-09-25", end:"2026-09-28", venue:"太平洋長灘", city:"田原市", address:"愛知県田原市赤羽根町大石", mapQuery:"太平洋ロングビーチ", disciplineKey:null, hkg:false },
  { sport:"乒乓球", event:"乒乓球", start:"2026-09-20", end:"2026-09-28", venue:"SKY HALL 豐田", city:"豐田市", address:"愛知県豊田市八幡町1-20", mapQuery:"スカイホール豊田", disciplineKey:"table_tennis", hkg:true },
  { sport:"跆拳道", event:"競技、品勢、虛擬跆拳道", start:"2026-10-01", end:"2026-10-03", venue:"豐橋市綜合體育館", city:"豐橋市", address:"愛知県豊橋市神野新田町メノ割1-3", mapQuery:"豊橋市総合体育館", disciplineKey:"taekwondo", hkg:true },
  { sport:"網球", event:"網球", start:"2026-09-27", end:"2026-10-03", venue:"名古屋市東山公園網球中心", city:"名古屋市", address:"愛知県名古屋市天白区天白町大字八事裏山60-19", mapQuery:"東山公園テニスセンター", disciplineKey:"tennis", hkg:true },
  { sport:"軟式網球", event:"軟式網球", start:"2026-09-18", end:"2026-09-23", venue:"名古屋市東山公園網球中心", city:"名古屋市", address:"愛知県名古屋市天白区天白町大字八事裏山60-19", mapQuery:"東山公園テニスセンター", disciplineKey:null, hkg:false },
  { sport:"三項鐵人", event:"三項鐵人", start:"2026-09-20", end:"2026-09-21", venue:"蒲郡市三項鐵人賽場", city:"蒲郡市", address:"愛知県蒲郡市", mapQuery:"蒲郡市 三項鉄人", mapLinkOverride:"https://maps.app.goo.gl/GZxBTVma97PBwJN56?g_st=ic", disciplineKey:"triathlon", hkg:true },
  { sport:"排球", event:"室內排球", start:"2026-09-16", end:"2026-10-03", venue:"岡崎中央綜合公園體育館", city:"岡崎市", address:"愛知県岡崎市高隆寺町字峠1", mapQuery:"岡崎中央総合公園総合体育館", disciplineKey:"volleyball_indoor", hkg:true },
  { sport:"排球", event:"室內排球", start:"2026-09-16", end:"2026-10-03", venue:"小牧市體育館 (Park Arena Komaki)", city:"小牧市", address:"愛知県小牧市間々原新田737", mapQuery:"パークアリーナ小牧", disciplineKey:"volleyball_indoor", hkg:true },
  { sport:"排球", event:"沙灘排球", start:"2026-09-20", end:"2026-10-03", venue:"碧南綠地沙灘排球場", city:"碧南市", address:"愛知県碧南市港本町", mapQuery:"碧南緑地ビーチコート", disciplineKey:"volleyball_beach", hkg:true },
  { sport:"舉重", event:"舉重", start:"2026-09-23", end:"2026-09-29", venue:"名古屋市中小企業振興會館", city:"名古屋市", address:"愛知県名古屋市千種区吹上2-6-3", mapQuery:"名古屋市中小企業振興会館", disciplineKey:"weightlifting", hkg:true },
  { sport:"摔跤", event:"摔跤", start:"2026-09-30", end:"2026-10-03", venue:"名古屋市稻永體育中心", city:"名古屋市", address:"愛知県名古屋市港区野跡5-1-10", mapQuery:"名古屋市稲永スポーツセンター", disciplineKey:"wrestling", hkg:true },
  { sport:"武術", event:"套路、散打", start:"2026-09-20", end:"2026-09-24", venue:"愛知縣武道館", city:"名古屋市", address:"愛知県名古屋市港区丸池町1-1-4", mapQuery:"愛知県武道館", disciplineKey:"wushu", hkg:true },
];

// assign stable ids
EVENTS.forEach((e, i) => { e.id = i + 1; });

// Hong Kong delegation athlete rosters, keyed by disciplineKey.
// Athletes are listed as { g: "M"|"F", en: "English name", zh: "Chinese name" },
// in the order given by the official delegation list (already grouped by discipline).
const ROSTER = {
  aquatics_artisticswimming: {
    label: "Aquatics - ArtisticSwimming 韻律泳",
    athletes: [
      { g:"F", en:"CHAN Anna Brontie", zh:"陳思全" },
      { g:"F", en:"CHENG Jasmine", zh:"鄭梓翎" },
      { g:"F", en:"CHU Ka Wing Katherine", zh:"朱家泳" },
      { g:"F", en:"HUNG Sze Ching", zh:"熊詩晴" },
      { g:"F", en:"LAM Azland Chi Yeung", zh:"林資洋" },
      { g:"F", en:"LAM Nok Yan Lauren", zh:"藍諾恩" },
      { g:"F", en:"LEE Chi Yin", zh:"李姿賢" },
      { g:"F", en:"WONG Wing Ka", zh:"黃穎嘉" },
      { g:"F", en:"YANG Zihua", zh:"楊姿華" },
      { g:"F", en:"ZHAO Meyako", zh:"趙詩韻" },
    ]
  },
  aquatics_diving: {
    label: "Aquatics - Diving 跳水",
    athletes: [
      { g:"M", en:"YUEN Pak Kwan Marcus", zh:"阮柏鈞" },
      { g:"F", en:"CHAN Tsz Ming", zh:"陳梓銘" },
      { g:"M", en:"YUEN Pak Yin Curtis", zh:"阮柏彥" },
      { g:"F", en:"LEUNG Ka Sin", zh:"梁家嫸" },
    ]
  },
  aquatics_swimming: {
    label: "Aquatics - Swimming 游泳",
    athletes: [
      { g:"M", en:"CHAN Tsz Chiu", zh:"陳鎡樵" },
      { g:"F", en:"CHAN Tsz Yu Ashley", zh:"陳梓瑜" },
      { g:"M", en:"CHEN Eric Q", zh:"陳慶煌" },
      { g:"F", en:"CHEUNG Sum Yuet Cindy", zh:"張心悅" },
      { g:"M", en:"CHEUNG Chi Kit Nicholas", zh:"張智傑" },
      { g:"F", en:"GAO Jialian Candice", zh:"高嘉蓮" },
      { g:"M", en:"CHILLINGWORTH Adam John", zh:"趙浩俊" },
      { g:"F", en:"HAUGHEY Siobhan Bernadette", zh:"何詩蓓" },
      { g:"M", en:"HO Chung Lun", zh:"何仲綸" },
      { g:"F", en:"KAN Cheuk Tung Natalie", zh:"簡綽桐" },
      { g:"M", en:"HO Ian Yentou", zh:"何甄陶" },
      { g:"F", en:"LAM Chelsie", zh:"林韵晴" },
      { g:"M", en:"HOFSTEDE Adam Marcel", zh:"何沛熹" },
      { g:"F", en:"LAM Pac Tung Nikita", zh:"林柏彤" },
      { g:"M", en:"KOO Ralph Yat Ho", zh:"古逸豪" },
      { g:"F", en:"LI Sum Yiu", zh:"李芯瑤" },
      { g:"M", en:"KWAN Hayden", zh:"關鵬" },
      { g:"F", en:"MA Gilaine", zh:"馬紫玲" },
      { g:"M", en:"KWAN Nicholas", zh:"關子博" },
      { g:"F", en:"MAN Wui Kiu", zh:"文薈喬" },
      { g:"M", en:"LAI King Wo Barry", zh:"賴敬和" },
      { g:"F", en:"MATHIS Mya Lynn", zh:"文雪兒" },
      { g:"M", en:"LAU Kin Hei James", zh:"劉建希" },
      { g:"F", en:"NG Cheuk Yan", zh:"吳綽恩" },
      { g:"M", en:"LI Sing Hoi", zh:"李昇海" },
      { g:"F", en:"NG Lai Wa", zh:"吳麗華" },
      { g:"M", en:"LO Tsz Lam", zh:"盧梓霖" },
      { g:"F", en:"WANG Xintong", zh:"王欣桐" },
      { g:"M", en:"MAK Sai Ting Adam", zh:"麥世霆" },
      { g:"F", en:"YEUNG Hoi Ching", zh:"楊凱晴" },
      { g:"M", en:"TSUI Yik Ki", zh:"徐奕祺" },
      { g:"M", en:"WAN Chun Lim", zh:"尹進廉" },
      { g:"M", en:"WANG Yi Shun", zh:"王一舜" },
      { g:"M", en:"YU Dongqi", zh:"余東豈" },
    ]
  },
  aquatics_water_polo: {
    label: "Aquatics - Water Polo 水球",
    athletes: [
      { g:"M", en:"CHAN Leong Medwin", zh:"陳亮" },
      { g:"M", en:"CHAN Lut Yin", zh:"陳律言" },
      { g:"M", en:"CHENG Hei Chun", zh:"鄭希駿" },
      { g:"M", en:"CHENG Hei Man", zh:"鄭希文" },
      { g:"M", en:"CHEUNG Cheuk Hei", zh:"張焯稀" },
      { g:"M", en:"CHING Tsz Shun", zh:"程梓舜" },
      { g:"M", en:"CHOI Hin Kit Gilman", zh:"蔡顯傑" },
      { g:"M", en:"FUNG Kong Ching", zh:"馮剛政" },
      { g:"M", en:"FUNG Kong Chun", zh:"馮剛俊" },
      { g:"M", en:"HO Jason", zh:"何浚鏗" },
      { g:"M", en:"LEE Tsz Wun Matthew", zh:"李旨桓" },
      { g:"M", en:"LIU Yeu Yen Ians", zh:"廖宇玄" },
      { g:"M", en:"TSANG Ho Lam", zh:"曾浩霖" },
      { g:"M", en:"YUEN Shing Yau", zh:"阮承佑" },
      { g:"M", en:"ZHANG Tsz Hin", zh:"張梓軒" },
    ]
  },
  archery: {
    label: "Archery 射箭",
    athletes: [
      { g:"M", en:"KWOK Yin Chai", zh:"郭賢霽" },
      { g:"F", en:"CHENG Hung Ting", zh:"鄭鴻婷" },
      { g:"F", en:"WANG Cheuk Ying", zh:"王卓盈" },
      { g:"F", en:"WONG Yuk Sheung", zh:"黃玉嫦" },
    ]
  },
  athletics: {
    label: "Athletics 田徑",
    athletes: [
      { g:"M", en:"CHAN Chun Ho", zh:"陳俊浩" },
      { g:"F", en:"CHAN Pui Kei", zh:"陳佩琦" },
      { g:"M", en:"CHAN Yat Lok", zh:"陳一樂" },
      { g:"F", en:"CHEUNG Ching Laam Priscilla", zh:"張靜嵐" },
      { g:"M", en:"CHEUNG Ho Hin", zh:"張灝軒" },
      { g:"F", en:"CHOI Season", zh:"蔡思晨" },
      { g:"M", en:"CHEUNG Wang Fung", zh:"張宏峰" },
      { g:"F", en:"CHOW Chi Kiu", zh:"鄒子蕎" },
      { g:"M", en:"CHIN Man Kit", zh:"錢文傑" },
      { g:"F", en:"CHUNG Wai Yan", zh:"鍾慧欣" },
      { g:"M", en:"CHUNG Long Hei Cyrus", zh:"鍾朗晞" },
      { g:"F", en:"JIA Wai Yin", zh:"賈慧妍" },
      { g:"M", en:"CHUNG Tsz Sing", zh:"鍾梓聖" },
      { g:"F", en:"KARLSSON Jane Christa MingSuet", zh:"徐穎恩" },
      { g:"M", en:"HO Ho Wai", zh:"何澔維" },
      { g:"F", en:"LEUNG Kwan Yi", zh:"梁筠宜" },
      { g:"M", en:"JOHANNSSON MagnusProstur", zh:"吳君浩" },
      { g:"F", en:"LO Ying Chiu", zh:"羅映潮" },
      { g:"M", en:"KENNELLY Michael John", zh:"祈尊康" },
      { g:"F", en:"LUO Tsz Yuen", zh:"羅芷元" },
      { g:"M", en:"KHAN Mohammad Kamran", zh:"金智武" },
      { g:"F", en:"MA Ying Wen Ashleigh", zh:"馬穎雯" },
      { g:"M", en:"KWOK Chun Ting", zh:"郭俊廷" },
      { g:"F", en:"PAK Hoi Man Chloe", zh:"白凱文" },
      { g:"M", en:"LAM Vincent Leslie", zh:"林穎璋" },
      { g:"F", en:"POON Hang Wai", zh:"潘幸慧" },
      { g:"M", en:"LEE Hong Kit", zh:"李康傑" },
      { g:"F", en:"SHING Cho Yan", zh:"盛楚殷" },
      { g:"M", en:"LIN Mingfu", zh:"林銘夫" },
      { g:"F", en:"WONG Cheuk Ning", zh:"黃卓寧" },
      { g:"M", en:"LIU Hiu Long", zh:"廖曉朗" },
      { g:"F", en:"WONG Wan Chi", zh:"黃韻之" },
      { g:"M", en:"WONG Pak Hang", zh:"黃珀恒" },
      { g:"F", en:"YAU Sin Ting Nicole", zh:"邱蒨庭" },
      { g:"M", en:"YIP King Wai", zh:"葉景維" },
      { g:"F", en:"YU Pui Yi", zh:"庾沛怡" },
      { g:"F", en:"YUE Nga Yan", zh:"俞雅欣" },
    ]
  },
  badminton: {
    label: "Badminton 羽毛球",
    athletes: [
      { g:"M", en:"CHAN Yin Chak", zh:"陳延澤" },
      { g:"F", en:"LIANG Ka Wing", zh:"梁珈穎" },
      { g:"M", en:"CHEUNG Sai Shing", zh:"張世成" },
      { g:"F", en:"LO Sin Yan Happy", zh:"盧善恩" },
      { g:"M", en:"DENG Chi Fai", zh:"鄧志輝" },
      { g:"F", en:"LUI Lok Lok", zh:"呂樂樂" },
      { g:"M", en:"GUNAWAN Jason", zh:"吳英倫" },
      { g:"F", en:"MEHTA Saloni Samirbhai", zh:"馬子雪" },
      { g:"M", en:"HUNG Kuei Chun", zh:"洪魁駿" },
      { g:"F", en:"NG Tsz Yau", zh:"吳芷柔" },
      { g:"M", en:"LAM Ka To", zh:"林家滔" },
      { g:"F", en:"TSANG Hiu Yan", zh:"曾曉昕" },
      { g:"M", en:"LEE Cheuk Yiu", zh:"李卓耀" },
      { g:"F", en:"TSE Ying Suet", zh:"謝影雪" },
      { g:"M", en:"LUI Chun Wai", zh:"呂俊瑋" },
      { g:"F", en:"WONG Yi", zh:"黃怡" },
      { g:"M", en:"NG Ka Long Angus", zh:"伍家朗" },
      { g:"F", en:"YEUNG Nga Ting", zh:"楊雅婷" },
      { g:"M", en:"YEUNG Shing Choi", zh:"楊盛才" },
      { g:"F", en:"YEUNG Pui Lam", zh:"楊霈霖" },
    ]
  },
  baseball: {
    label: "Baseball 棒球",
    athletes: [
      { g:"M", en:"CHAN Alexander Cheuk Hei", zh:"陳卓希" },
      { g:"M", en:"CHAN Cheuk Kiu", zh:"陳卓喬" },
      { g:"M", en:"CHAN Sze Yue", zh:"陳思宇" },
      { g:"M", en:"CHENG Hoi Ting", zh:"鄭鎧霆" },
      { g:"M", en:"CHENG Yu Hin Oscar", zh:"鄭宇軒" },
      { g:"M", en:"FONG Chun Hei", zh:"方溍希" },
      { g:"M", en:"FUNG Anson", zh:"馮安生" },
      { g:"M", en:"HUNG Wang Chak", zh:"洪泓澤" },
      { g:"M", en:"KWOK Ching Connor", zh:"郭靖" },
      { g:"M", en:"LAM Lai Him", zh:"林澧謙" },
      { g:"M", en:"LEE Ho Chi Ryan", zh:"李浩誌" },
      { g:"M", en:"LEE Long Ching", zh:"李朗晴" },
      { g:"M", en:"LEUNG Ka Ho Sam", zh:"梁家豪" },
      { g:"M", en:"MA Hon Man Ashley", zh:"馬翰文" },
      { g:"M", en:"MOK Chun Lam", zh:"莫竣林" },
      { g:"M", en:"MOK Chun Pui", zh:"莫竣棓" },
      { g:"M", en:"NG Yau Pang", zh:"吳有朋" },
      { g:"M", en:"TAM Ho Yin Benny", zh:"譚浩賢" },
      { g:"M", en:"TSANG Kin Nam", zh:"曽健南" },
      { g:"M", en:"TSUI Chak Pui", zh:"徐澤培" },
      { g:"M", en:"WEN Tsz Yin Jordan", zh:"溫子賢" },
      { g:"M", en:"WONG Yui Fung", zh:"黃睿鋒" },
      { g:"M", en:"WU Tsz Tung", zh:"胡子彤" },
      { g:"M", en:"YUNG Tsun Wai", zh:"翁浚暐" },
    ]
  },
  basketball_3x3: {
    label: "Basketball - 3 x 3 3x3 籃球",
    athletes: [
      { g:"M", en:"CHAN Man To", zh:"陳文滔" },
      { g:"M", en:"TANG Lik Ka", zh:"鄧力嘉" },
      { g:"M", en:"WU Wai Tsun", zh:"吳委峻" },
      { g:"M", en:"YANG Bo Wen Ivan", zh:"楊博文" },
    ]
  },
  basketball_5x5: {
    label: "Basketball - 5 x 5 5x5 籃球",
    athletes: [
      { g:"F", en:"CHEUNG Chor Ying", zh:"張楚盈" },
      { g:"F", en:"CHIU Ka Yu", zh:"趙珈萮" },
      { g:"F", en:"KWAN Hoi Pui", zh:"關海珮" },
      { g:"F", en:"LAU Sheung Hok", zh:"劉常學" },
      { g:"F", en:"LI Tsz Kwan", zh:"李祉均" },
      { g:"F", en:"MA Tan Fung", zh:"馬丹鳳" },
      { g:"F", en:"NG Yan Tung", zh:"吳欣潼" },
      { g:"F", en:"TONG Hiu Lui", zh:"唐曉蕾" },
      { g:"F", en:"TSUI Wing Yu", zh:"徐穎榆" },
      { g:"F", en:"WONG Ching Hei Christy", zh:"黃靖浠" },
      { g:"F", en:"WONG Nga Ting", zh:"黃雅婷" },
      { g:"F", en:"YAM Hui Yin", zh:"任栩燕" },
    ]
  },
  canoe_sprint: {
    label: "Canoe - Sprint 獨木舟-競速",
    athletes: [
      { g:"M", en:"CHANG Long Yin", zh:"張朗然" },
      { g:"M", en:"CHEUNG Tsz Chung", zh:"張子衝" },
      { g:"M", en:"LO Wai Lok", zh:"盧瑋珞" },
      { g:"M", en:"SO Pak Yin", zh:"蘇柏賢" },
    ]
  },
  cricket: {
    label: "Cricket 板球",
    athletes: [
      { g:"M", en:"Khan HAFEEZ", zh:"簡凱非" },
      { g:"M", en:"Babar HAYAT", zh:"巴巴爾哈亞特" },
      { g:"M", en:"Rajab HUSSAIN", zh:"金少明" },
      { g:"M", en:"Anas KHAN", zh:"簡安納斯" },
      { g:"M", en:"Ehsan KHAN", zh:"埃桑汗" },
      { g:"M", en:"Mohammad Hassan KHAN", zh:"簡和智" },
      { g:"M", en:"Shiv MATHUR", zh:"馬士毅" },
      { g:"M", en:"Ghazanfar MOHAMMAD", zh:"毛家星" },
      { g:"M", en:"Nizakat Khan MOHAMMAD", zh:"穆罕默德汗" },
      { g:"M", en:"Waheed MOHAMMAD", zh:"華希" },
      { g:"M", en:"Yasim MURTAZA", zh:"穆達仁" },
      { g:"M", en:"Nasrulla RANA", zh:"莫家誠" },
      { g:"M", en:"Anshuman RATH", zh:"陽神太" },
      { g:"M", en:"Ayush Ashish SHUKLA", zh:"賀鈺成" },
      { g:"M", en:"Shahid WASIF", zh:"華山希" },
    ]
  },
  cycling_track_road: {
    label: "Cycling - Track/Road單車 (場地/公路)",
    athletes: [
      { g:"M", en:"CHU Tsun Wai", zh:"朱浚瑋" },
      { g:"F", en:"CHEUNG Li Tong Guardiola", zh:"張履檾" },
      { g:"M", en:"LAU Wan Yau Vincent", zh:"劉允祐" },
      { g:"F", en:"CHING Yin Shan", zh:"程嬿珊" },
      { g:"M", en:"MA Yik Fei", zh:"馬繹斐" },
      { g:"F", en:"KWAN Tsz Kwan", zh:"關旨君" },
      { g:"M", en:"MOK Tsz Chun", zh:"莫沚駿" },
      { g:"F", en:"LEE Sze Wing", zh:"李思穎" },
      { g:"M", en:"MOW Ching Yin", zh:"繆正賢" },
      { g:"F", en:"LEUNG Wing Yee", zh:"梁穎儀" },
      { g:"M", en:"NG Pak Hang", zh:"伍柏亨" },
      { g:"F", en:"NG Sze Wing", zh:"吳思穎" },
      { g:"M", en:"NG Po Li", zh:"吳保利" },
      { g:"F", en:"TUNG Phoebe", zh:"童森" },
      { g:"M", en:"TO Cheuk Hei", zh:"杜棹熙" },
      { g:"F", en:"YEUNG Cho Yiu", zh:"楊礎搖" },
      { g:"M", en:"TSO Kai Kwong", zh:"曹棨光" },
      { g:"M", en:"WU Chun Yin", zh:"胡俊賢" },
      { g:"M", en:"YIP Hon Man", zh:"葉漢文" },
      { g:"M", en:"YUNG Tsun Ho", zh:"翁浚皓" },
    ]
  },
  cycling_bmx_racing: {
    label: "Cycling - BMX Racing單車 (小輪車競速)",
    athletes: [
      { g:"F", en:"KWOK Noel Vanessa", zh:"郭澄" },
    ]
  },
  cycling_mountainbike: {
    label: "Cycling - MountainBike 單車 (山地)",
    athletes: [
      { g:"M", en:"LAI Chun Kin", zh:"賴俊健" },
      { g:"F", en:"KWAN Tsz Kwan", zh:"關旨君" },
      { g:"F", en:"YU Hoi Tik", zh:"余海廸" },
    ]
  },
  dancesport_breaking: {
    label: "DanceSport- Breaking體育舞蹈 - 霹靂舞",
    athletes: [
      { g:"M", en:"SZE Ka Yam", zh:"施嘉鑫" },
    ]
  },
  equestrian: {
    label: "Equestrian 馬術",
    athletes: [
      { g:"M", en:"LAM Patrick", zh:"林立信" },
      { g:"F", en:"CHENG Kai Hei Yuddy", zh:"鄭楷㬢" },
      { g:"M", en:"SU Yu Xuan", zh:"蘇昱軒" },
      { g:"F", en:"Clarissa Christine LukeDE LYRA", zh:"黎嘉怡" },
      { g:"F", en:"FARDEL Nicole Michele", zh:"吳蓓華" },
      { g:"F", en:"HO Yuen Yan Annie", zh:"何苑欣" },
      { g:"F", en:"LAI Jacqueline Jing-Man", zh:"賴楨敏" },
      { g:"F", en:"LALIVE D'EPINAY Sheikara Asia", zh:"韋娜" },
      { g:"F", en:"LI Kendra Victoria", zh:"李逸寧" },
    ]
  },
  esports: {
    label: "Esports 電子競技",
    athletes: [
      { g:"M", en:"CHAN Cheuk Kit", zh:"陳卓傑" },
      { g:"F", en:"FAN Hoi Ching", zh:"范凱晴" },
      { g:"M", en:"CHAN Chun Kit", zh:"陳進杰" },
      { g:"F", en:"WONG Fanny Fung Ching", zh:"黃鳳湞" },
      { g:"M", en:"CHAN Jeffrey", zh:"陳子賢" },
      { g:"F", en:"YU Wing Lim", zh:"余穎廉" },
      { g:"M", en:"CHAN Kam Tung", zh:"陳錦東" },
      { g:"M", en:"CHAN Kit Kuen", zh:"陳杰權" },
      { g:"M", en:"CHAN Pan Yuen", zh:"陳品源" },
      { g:"M", en:"CHAN Tsz Hin Justin", zh:"陳子軒" },
      { g:"M", en:"CHAU Shu Tak", zh:"鄒樹德" },
      { g:"M", en:"CHEN Hongsen", zh:"陳泓森" },
      { g:"M", en:"CHENG Ka Hin", zh:"鄭嘉軒" },
      { g:"M", en:"CHEUNG Ming Yun", zh:"張銘潤" },
      { g:"M", en:"CHEUNG Sze Hin", zh:"張思軒" },
      { g:"M", en:"CHUI Sum Ki", zh:"徐琛淇" },
      { g:"M", en:"DENG Xin Zhan", zh:"鄧幸展" },
      { g:"M", en:"KONG Tsz Kin", zh:"江子健" },
      { g:"M", en:"KWOK Ho Wa", zh:"郭浩樺" },
      { g:"M", en:"LAI Kau Ming", zh:"賴教銘" },
      { g:"M", en:"LAM Kwun Wang Kevin", zh:"林冠宏" },
      { g:"M", en:"LAW Hing Lung", zh:"羅慶隆" },
      { g:"M", en:"LEUNG Ka Kit", zh:"梁家杰" },
      { g:"M", en:"LI Hin Hei", zh:"李衍熙" },
      { g:"M", en:"LI Ka Hing", zh:"李嘉慶" },
      { g:"M", en:"LI Sau Nam", zh:"李修楠" },
      { g:"M", en:"LI Tak Cheung", zh:"李德祥" },
      { g:"M", en:"LING Kai Wing", zh:"凌啟榮" },
      { g:"M", en:"LOO Kin Shing", zh:"盧建成" },
      { g:"M", en:"NG Cheuk Lun Jason", zh:"伍焯綸" },
      { g:"M", en:"PANG Ka Kit", zh:"彭嘉傑" },
      { g:"M", en:"TSANG Tak Lam", zh:"曾德霖" },
      { g:"M", en:"TSOI Ka Po", zh:"蔡家寶" },
      { g:"M", en:"TSUI Chi Kan", zh:"徐志勤" },
      { g:"M", en:"TSUI Chun Yin Rico", zh:"徐晉賢" },
      { g:"M", en:"WANG Calvin Jacob", zh:"王遠誠" },
      { g:"M", en:"WANG Mingjie", zh:"王明杰" },
      { g:"M", en:"WONG Kai Hin Jonathan", zh:"黃啟軒" },
      { g:"M", en:"WONG Yu Hin", zh:"黃宇軒" },
      { g:"M", en:"WONG Yuk Cheung", zh:"黃育祥" },
      { g:"M", en:"WU Tsun Wai", zh:"胡峻威" },
      { g:"M", en:"YEH Man Ho", zh:"葉文豪" },
      { g:"M", en:"ZHENG Ka Yeung", zh:"鄭嘉揚" },
    ]
  },
  fencing: {
    label: "Fencing 劍撃",
    athletes: [
      { g:"M", en:"CHAN Lok Hei Royce", zh:"陳樂熹" },
      { g:"F", en:"CHAN Nok Sze Daphne", zh:"陳諾思" },
      { g:"M", en:"CHEUNG Ka Long", zh:"張家朗" },
      { g:"F", en:"CHAN Wai Ling", zh:"陳渭泠" },
      { g:"M", en:"CHOI Chun Yin Ryan", zh:"蔡俊彥" },
      { g:"F", en:"CHENG Hiu Wai Valerie", zh:"鄭曉為" },
      { g:"M", en:"FONG Hoi Sun", zh:"方凱申" },
      { g:"F", en:"CHU Ka Mong", zh:"朱嘉望" },
      { g:"M", en:"HO Pak Lam Hugo", zh:"何柏霖" },
      { g:"F", en:"CHU Wing Kiu", zh:"朱詠翹" },
      { g:"M", en:"HO Shing Him Harris", zh:"何承謙" },
      { g:"F", en:"HSIEH Kaylin Sin Yan", zh:"佘繕妡" },
      { g:"M", en:"HO Sze Long Aaron", zh:"何思朗" },
      { g:"F", en:"LAU Yee Ching", zh:"劉綺程" },
      { g:"M", en:"HO Wai Hang", zh:"何瑋桁" },
      { g:"F", en:"LEUNG Nok Man Laren", zh:"梁洛文" },
      { g:"M", en:"LAU Ho Fung", zh:"劉昊峯" },
      { g:"F", en:"LEUNG Ya Lei Janelle", zh:"梁雅蕾" },
      { g:"M", en:"LEUNG Chin Yu", zh:"梁千雨" },
      { g:"F", en:"SIT Summer Fay", zh:"薛雅齊" },
      { g:"M", en:"LEUNG Tin Ching", zh:"梁天晴" },
      { g:"F", en:"WU Haidi", zh:"吳海諦" },
      { g:"M", en:"NG Ho Tin", zh:"吳浩天" },
      { g:"F", en:"WU Sophia", zh:"符妤名" },
    ]
  },
  football: {
    label: "Football 足球",
    athletes: [
      { g:"M", en:"CHAN Kun Sun", zh:"陳冠燊" },
      { g:"F", en:"CHAN Chung Man Karri", zh:"陳頌文" },
      { g:"M", en:"CHEN Ngo Hin", zh:"陳傲軒" },
      { g:"F", en:"CHAN Tsz Shan", zh:"陳芷珊" },
      { g:"M", en:"CHEUNG Kwai Wa", zh:"張桂華" },
      { g:"F", en:"CHAN Wing Lam", zh:"陳穎霖" },
      { g:"M", en:"CHIN Yu Ho Jeffrey", zh:"秦宇灝" },
      { g:"F", en:"CHAN Yee Hing", zh:"陳綺馨" },
      { g:"M", en:"Helio Jose De Souza GONCALVES", zh:"艾里奧" },
      { g:"F", en:"CHEUNG Wai Ki", zh:"張煒琪" },
      { g:"M", en:"ICHIKAWA Sohgo", zh:"趙聡悟" },
      { g:"F", en:"CHU Sin Kwan", zh:"朱俏君" },
      { g:"M", en:"Krisna R KORANI", zh:"宏愷志" },
      { g:"F", en:"CHU So Kwan", zh:"朱素君" },
      { g:"M", en:"KWOK Chun Nok", zh:"郭縉諾" },
      { g:"F", en:"FU Chiu Man", zh:"傅昭文" },
      { g:"M", en:"LEE Chun Ting", zh:"李俊霆" },
      { g:"F", en:"FUNG Sharon", zh:"馮雪雯" },
      { g:"M", en:"LEE Lok Him", zh:"李樂謙" },
      { g:"F", en:"KO Pak Ling Lucia", zh:"高栢齡" },
      { g:"M", en:"LOONG Tsz Hin", zh:"龍梓軒" },
      { g:"F", en:"KWAN Wing Yu", zh:"關泳瑜" },
      { g:"M", en:"MA Hei Wai", zh:"馬希偉" },
      { g:"F", en:"LEE Yi Yan", zh:"李懿茵" },
      { g:"M", en:"NG Yu Hei", zh:"吳宇曦" },
      { g:"F", en:"LEUNG Hong Kiu Anke", zh:"梁匡蕎" },
      { g:"M", en:"NGAN Cheuk Pan", zh:"顏卓彬" },
      { g:"F", en:"LI Hau Yi", zh:"李巧怡" },
      { g:"M", en:"Anthony Francis PINTO", zh:"杜俊暉" },
      { g:"F", en:"LI Sze Ying", zh:"李思瑩" },
      { g:"M", en:"POON Sheung Hei", zh:"潘尚希" },
      { g:"F", en:"LUK Sean Hoi Ching", zh:"陸愷晴" },
      { g:"M", en:"Matthew Luke SLATTERY", zh:"馬斐" },
      { g:"F", en:"MA Chak Shun", zh:"馬澤純" },
      { g:"M", en:"SUNG Wang Ngai Kohki Takizawa", zh:"宋紘毅" },
      { g:"F", en:"NG Cheuk Wai", zh:"吳卓蔚" },
      { g:"M", en:"TSANG Lok To Jeremy", zh:"曾樂圖" },
      { g:"F", en:"TSANG Lai Mae Halasan", zh:"曾麗薇" },
      { g:"M", en:"TSANG Yi Hang Ellison", zh:"曾以行" },
      { g:"F", en:"TSANG Pak Tung", zh:"曾柏同" },
      { g:"M", en:"Michael Chibuikem UDEBULUZOR", zh:"米高" },
      { g:"F", en:"WAI Yuen Ting", zh:"韋婉婷" },
      { g:"M", en:"WU Chun Ming", zh:"胡晉銘" },
      { g:"F", en:"WEI Lan", zh:"魏嵐" },
      { g:"M", en:"YIM Kai Cheuk", zh:"嚴啟倬" },
      { g:"F", en:"WU Choi Yiu", zh:"胡彩瑤" },
    ]
  },
  golf: {
    label: "Golf 高爾夫球",
    athletes: [
      { g:"M", en:"CHEUNG Matthew Hung Hai", zh:"張雄熙" },
      { g:"F", en:"DING Wai Chung Virginie", zh:"丁慧中" },
      { g:"M", en:"HAK Shun Yat", zh:"黑純一" },
      { g:"F", en:"HAN Sophie", zh:"韓紫琳" },
      { g:"M", en:"KHO Taichi", zh:"許龍一" },
      { g:"F", en:"LAU Arianna", zh:"劉弦" },
    ]
  },
  gymnastics_artistic: {
    label: "Gymnastics - Artistic競技體操",
    athletes: [
      { g:"M", en:"NG Ka Ki", zh:"吳家祺" },
      { g:"F", en:"CHEN Hoi Yuen Joanne", zh:"曾凱緣" },
      { g:"F", en:"WONG Tim Ching Kiana", zh:"黃恬晴" },
    ]
  },
  gymnastics_rhythmic: {
    label: "Gymnastics - Rhythmic 藝術體操",
    athletes: [
      { g:"F", en:"LI Ting Huen", zh:"李庭萱" },
    ]
  },
  gymnastics_trampoline: {
    label: "Gymnastics - Trampoline 彈網",
    athletes: [
      { g:"M", en:"LAU Long Fung Ronald", zh:"劉朗風" },
      { g:"F", en:"LIU Kit Ying Jennifer May Kwan", zh:"劉潔瑩" },
      { g:"M", en:"LEE Kwun Wai", zh:"李冠煒" },
      { g:"F", en:"XIAO Yiyao", zh:"蕭逸瑤" },
    ]
  },
  handball: {
    label: "Handball 手球",
    athletes: [
      { g:"M", en:"CHAN Tsz Long", zh:"陳梓朗" },
      { g:"F", en:"CHAN Kam Ling", zh:"陳錦玲" },
      { g:"M", en:"CHUNG Shu Yin", zh:"鍾樹賢" },
      { g:"F", en:"CHEUNG Man Shan", zh:"張敏珊" },
      { g:"M", en:"HON Hok Hei", zh:"韓學曦" },
      { g:"F", en:"CHEUNG Mei Ngo", zh:"張美娥" },
      { g:"M", en:"KAN Yik Fai", zh:"簡翊暉" },
      { g:"F", en:"CHONG Sze Ki", zh:"莊斯琪" },
      { g:"M", en:"KAN Yik Man", zh:"簡翊文" },
      { g:"F", en:"FUNG Sze Ming", zh:"馮詩銘" },
      { g:"M", en:"LAU Ka Yiu", zh:"劉嘉堯" },
      { g:"F", en:"HUNG Cheuk Kiu", zh:"洪卓翹" },
      { g:"M", en:"LAW Chun Yiu", zh:"羅俊耀" },
      { g:"F", en:"HUNG Sin Yu", zh:"孔倩瑜" },
      { g:"M", en:"LEE Hau Yu", zh:"李効諭" },
      { g:"F", en:"LIU Ho Ching", zh:"廖可晴" },
      { g:"M", en:"LEE Siu Chung", zh:"李少聰" },
      { g:"F", en:"LO Kei Laam", zh:"盧紀嵐" },
      { g:"M", en:"LEUNG Laam Hei", zh:"梁嵐熹" },
      { g:"F", en:"SZE Yan Yee", zh:"施欣儀" },
      { g:"M", en:"LIN Yun To Toby", zh:"連潤滔" },
      { g:"F", en:"TAI Tsz Yi", zh:"戴子怡" },
      { g:"M", en:"TSE Wing Fai", zh:"謝永輝" },
      { g:"F", en:"TSANG Yuen Lam", zh:"曾婉琳" },
      { g:"M", en:"WONG Kin", zh:"黃健" },
      { g:"F", en:"WONG Yee Ting", zh:"黃綺婷" },
      { g:"M", en:"WONG Ling Chung", zh:"黃靈聰" },
      { g:"F", en:"WU Lei Ling", zh:"鄔梨鈴" },
      { g:"M", en:"YIP Chi Kuen Aison", zh:"葉滋權" },
      { g:"F", en:"YEUNG Chun Yan", zh:"楊俊欣" },
      { g:"M", en:"ZOU Yuk To", zh:"鄒旭濤" },
      { g:"F", en:"YIU Hei Yan", zh:"姚希欣" },
    ]
  },
  judo: {
    label: "Judo 柔道",
    athletes: [
      { g:"M", en:"LEE Kwok Wing", zh:"李玨穎" },
      { g:"F", en:"TSUI Shuk Ki", zh:"徐淑琪" },
      { g:"M", en:"MAK Hong Nin", zh:"麥康年" },
      { g:"F", en:"WONG Ka Lee", zh:"王嘉莉" },
      { g:"M", en:"WONG Ka Ki", zh:"王嘉祺" },
      { g:"F", en:"YEUNG Nok Lam", zh:"楊諾琳" },
    ]
  },
  karate: {
    label: "Karate 空手道",
    athletes: [
      { g:"M", en:"CHAU Ka Him", zh:"周家謙" },
      { g:"F", en:"LAU Mo Sheung Grace", zh:"劉慕裳" },
      { g:"M", en:"CHENG Hui Pan", zh:"鄭栩彬" },
      { g:"F", en:"TSANG Yee Ting", zh:"曾綺婷" },
      { g:"M", en:"HUNG Ho Wai Howard", zh:"洪晧崴" },
      { g:"F", en:"WONG Cheuk Lee", zh:"黃卓莉" },
      { g:"M", en:"LI Chi Kong", zh:"李智剛" },
      { g:"M", en:"TANG Yu Hin", zh:"鄧宇軒" },
    ]
  },
  modern_pentathlon: {
    label: "Modern Pentathlon現代五項",
    athletes: [
      { g:"M", en:"SHUM Chun Hei", zh:"岑晉熙" },
      { g:"F", en:"LIU Hei Yu", zh:"劉熙渝" },
    ]
  },
  padel: {
    label: "Padel 板網球",
    athletes: [
      { g:"M", en:"CHAU Kwan Lam Vincent", zh:"鄒君林" },
      { g:"F", en:"CHAN Hiu Laam", zh:"陳曉嵐" },
      { g:"M", en:"Mohammed Aziz KHAN", zh:"毅志恒" },
      { g:"F", en:"CHAN Wing Yau Venise", zh:"陳詠悠" },
      { g:"M", en:"LO Lok Pui Lawrence", zh:"羅樂培" },
      { g:"F", en:"LAU Hiu Wai", zh:"劉曉蔚" },
      { g:"M", en:"Sean Zachary LO ESCOTO", zh:"盧鐵風" },
      { g:"F", en:"LAW Yik Yan", zh:"羅易殷" },
    ]
  },
  roller_skateboarding: {
    label: "Roller Sports - Skateboarding 滾軸運動 - 滑板",
    athletes: [
      { g:"M", en:"GU Jiahuan", zh:"顧嘉洹" },
      { g:"F", en:"WAN Hiu Yin Yuna", zh:"溫曉妍" },
      { g:"M", en:"LI Pak Lam", zh:"李柏霖" },
      { g:"F", en:"WONG Yeuk Ching", zh:"黃若澄" },
      { g:"F", en:"WONG Yi Huen", zh:"黃爾萱" },
    ]
  },
  rowing: {
    label: "Rowing 賽艇",
    athletes: [
      { g:"M", en:"CHAN Chi Fung", zh:"陳至鋒" },
      { g:"F", en:"CHEUNG Pui Fong", zh:"張佩芳" },
      { g:"M", en:"CHAN Tik Lun", zh:"陳廸麟" },
      { g:"F", en:"CHEUNG Yuen Shan", zh:"張菀珊" },
      { g:"M", en:"CHEN Pak Hong", zh:"陳柏匡" },
      { g:"F", en:"CHUI Nga Man", zh:"崔雅文" },
      { g:"M", en:"CHIU Hin Chun", zh:"趙顯臻" },
      { g:"F", en:"HUI Wing Ki", zh:"許詠淇" },
      { g:"M", en:"HEAD Jaden Li", zh:"夏赫" },
      { g:"F", en:"HUNG Wing Yan Winne", zh:"洪詠甄" },
      { g:"M", en:"HO Wing Fai", zh:"何永輝" },
      { g:"F", en:"LEUNG Chi Ching Cici", zh:"梁智晴" },
      { g:"M", en:"LAM San Tung", zh:"林新棟" },
      { g:"F", en:"LEUNG King Wan", zh:"梁瓊允" },
      { g:"M", en:"LIU Sung Lai", zh:"廖崇禮" },
      { g:"F", en:"LEUNG Wing Wun", zh:"梁穎桉" },
      { g:"M", en:"MAK Ho Ching Jack", zh:"麥可靖" },
      { g:"F", en:"WONG Sheung Yee", zh:"黃湘儀" },
      { g:"M", en:"WONG Ching", zh:"黃鉦" },
    ]
  },
  rugby_sevens: {
    label: "Rugby Sevens 七人欖球",
    athletes: [
      { g:"M", en:"Matteo AVITABILE", zh:"" },
      { g:"F", en:"AU King To", zh:"歐景桃" },
      { g:"M", en:"Julien BOURRON", zh:"于力仁" },
      { g:"F", en:"AU YEUNG Sin Yi", zh:"歐陽倩怡" },
      { g:"M", en:"James Murray CHRISTIE", zh:"蔡紀駿" },
      { g:"F", en:"Emrin Micayla Barcellano BALTAZAR", zh:"畢凱桓" },
      { g:"M", en:"Max Cameron DENMARK", zh:"丹馬克" },
      { g:"F", en:"CHAN Chloe", zh:"陳穎" },
      { g:"M", en:"FONG Kit Fung", zh:"房傑鋒" },
      { g:"F", en:"CHAN Stephanie Chor Ki", zh:"陳楚琪" },
      { g:"M", en:"Liam Thomas HERBERT", zh:"靴貝特" },
      { g:"F", en:"CHAN Tsz Ching", zh:"陳芷晴" },
      { g:"M", en:"LEE Ka To Cado", zh:"李卡度" },
      { g:"F", en:"CHONG Ka Yan", zh:"莊嘉欣" },
      { g:"M", en:"Callum James MCCULLOUGH", zh:"麥浚勇" },
      { g:"F", en:"FORREST Shanna Sanman", zh:"霍山文" },
      { g:"M", en:"Alessandro NARDONI", zh:"虎拿當尼" },
      { g:"F", en:"HO Jessica Wai On", zh:"何維銨" },
      { g:"M", en:"Dafydd Bryn PHILLIPS", zh:"拜恩菲立斯" },
      { g:"F", en:"Julia Mibuy MBA OYANA", zh:"苗頌雅" },
      { g:"M", en:"Harry John James SAYERS", zh:"" },
      { g:"F", en:"NAM Ka Man", zh:"藍嘉敏" },
      { g:"M", en:"Rory Murdoch STEWART COX", zh:"" },
      { g:"F", en:"Natasha Shangwe OLSON-THORNE", zh:"高香慧" },
      { g:"M", en:"Matthew Samuel Martin WORLEY", zh:"王銘馳" },
      { g:"F", en:"Gabriella Eleanor Mary RIVERS", zh:"河春花" },
    ]
  },
  sailing: {
    label: "Sailing 帆船",
    athletes: [
      { g:"M", en:"Russell Williams AYLSWORTH", zh:"祥杰" },
      { g:"F", en:"HUANG Zixi", zh:"黃子曦" },
      { g:"M", en:"Tiago CHENG De VillemorSalgado", zh:"鄭祺翱" },
      { g:"F", en:"KONG Chloe", zh:"江芷棋" },
      { g:"M", en:"Nicholas Bezy HALLIDAY", zh:"貝俊龍" },
      { g:"F", en:"MAK Hiu Tung Tiffany", zh:"麥曉彤" },
      { g:"M", en:"Ethan Lachlan KIU", zh:"喬澔鏗" },
      { g:"F", en:"Stephanie Louise NORTON", zh:"洛雅怡" },
      { g:"M", en:"Louis Oliver POLSON", zh:"普令行" },
      { g:"F", en:"Emily Grace POLSON", zh:"普珺麗" },
      { g:"M", en:"Akira Luke SAKAI", zh:"阿輝" },
      { g:"F", en:"WONG MCCARLEY", zh:"黃曦慧" },
    ]
  },
  sailing_windsurfing: {
    label: "Sailing - Windsurfing帆船 - 滑浪風帆",
    athletes: [
      { g:"M", en:"CHENG Ching Yin", zh:"鄭清然" },
      { g:"F", en:"CHEUNG Tsz Yuet", zh:"張子悅" },
      { g:"M", en:"WONG Tsz Ho", zh:"黃梓豪" },
      { g:"F", en:"MA Kwan Ching", zh:"馬君正" },
    ]
  },
  shooting: {
    label: "Shooting射擊",
    athletes: [
      { g:"M", en:"CHEN Haohui", zh:"陳浩輝" },
      { g:"F", en:"SHING Ho Ching", zh:"成灝澂" },
    ]
  },
  softball: {
    label: "Softball 壘球",
    athletes: [
      { g:"F", en:"AU YEUNG Chi Ching", zh:"歐陽芷晴" },
      { g:"F", en:"CHAN Hiu Yan", zh:"陳曉欣" },
      { g:"F", en:"CHAN Sau Yui", zh:"陳秀蕊" },
      { g:"F", en:"CHAN Sze Wun Jasmine", zh:"陳思韻" },
      { g:"F", en:"CHAN Wing Sum", zh:"陳穎琛" },
      { g:"F", en:"CHAN Yee Lam", zh:"陳依琳" },
      { g:"F", en:"CHIU Hiu Wai", zh:"趙澆慰" },
      { g:"F", en:"CHIU Lee Chi", zh:"邱莉之" },
      { g:"F", en:"LAI Lok Tung", zh:"黎烙彤" },
      { g:"F", en:"LAM Pui Kwan", zh:"林佩君" },
      { g:"F", en:"LAM Tin Sum Tina", zh:"林天心" },
      { g:"F", en:"LAU Hiu Kwan", zh:"劉曉君" },
      { g:"F", en:"LAU Suet Man", zh:"劉雪汶" },
      { g:"F", en:"LEUNG Tsz Yan", zh:"梁芷茵" },
      { g:"F", en:"PONG Yui Chi", zh:"龐叡芝" },
      { g:"F", en:"WONG Cho Hei", zh:"黃楚曦" },
      { g:"F", en:"WONG Ho Ching", zh:"黃皓晴" },
    ]
  },
  sport_climbing: {
    label: "Sport Climbing 運動攀登",
    athletes: [
      { g:"M", en:"AU Chi Fung", zh:"歐智峰" },
      { g:"F", en:"LAM Cho Wing Jasmiki", zh:"林楚穎" },
      { g:"M", en:"CHAN Cheung Chi Shoji", zh:"陳翔志" },
      { g:"F", en:"LEUNG Sze Lai", zh:"梁思麗" },
      { g:"M", en:"CHAN Hugo Zhi-Tao", zh:"陳致滔" },
      { g:"F", en:"WONG Cheuk Kei", zh:"王卓琪" },
      { g:"M", en:"WONG Cheuk Nam", zh:"黃卓楠" },
      { g:"F", en:"WONG Hei Kiu Heidi", zh:"黃浠蕎" },
    ]
  },
  squash: {
    label: "Squash 壁球",
    athletes: [
      { g:"M", en:"LAI Cheuk Nam Matthew", zh:"黎卓楠" },
      { g:"F", en:"CHAN Sin Yuk", zh:"陳善鈺" },
      { g:"M", en:"LAU Tsz Kwan", zh:"劉子均" },
      { g:"F", en:"HO Tze Lok", zh:"何子樂" },
      { g:"M", en:"LEUNG Chi Hin Henry", zh:"梁子軒" },
      { g:"F", en:"LEE Ka Yi", zh:"李嘉兒" },
      { g:"M", en:"WONG Chi Him", zh:"黃祉謙" },
      { g:"F", en:"TSE Yee Lam Toby", zh:"謝依霖" },
    ]
  },
  table_tennis: {
    label: "Table Tennis 乒乓球",
    athletes: [
      { g:"M", en:"CHAN Baldwin Ho Wah", zh:"陳顥樺" },
      { g:"F", en:"DOO Hoi Kem", zh:"杜凱琹" },
      { g:"M", en:"KWAN Man Ho", zh:"關文皓" },
      { g:"F", en:"LAM Yee Lok", zh:"林依諾" },
      { g:"M", en:"LAM Siu Hang", zh:"林兆恒" },
      { g:"F", en:"LEE Hoi Man Karen", zh:"李凱敏" },
      { g:"M", en:"WONG Chun Ting", zh:"黃鎮廷" },
      { g:"F", en:"NG Wing Lam", zh:"吳詠琳" },
      { g:"M", en:"YIU Kwan To", zh:"姚鈞濤" },
      { g:"F", en:"SU Tsz Tung", zh:"蘇籽童" },
    ]
  },
  taekwondo: {
    label: "Taekwondo 跆拳道",
    athletes: [
      { g:"M", en:"LO Wai Fung", zh:"盧蔚豐" },
      { g:"F", en:"CHEUNG Ho Yan", zh:"張可欣" },
      { g:"M", en:"LUI Ching Nam", zh:"呂靖楠" },
      { g:"F", en:"HO Cathy Minly", zh:"何嘉雯" },
      { g:"F", en:"LAM Siu Wai", zh:"林小慧" },
      { g:"F", en:"LEE Tsz Ching", zh:"李子晴" },
    ]
  },
  tennis: {
    label: "Tennis 網球",
    athletes: [
      { g:"M", en:"CHENG Jack", zh:"程銘燦" },
      { g:"F", en:"CHONG Eudice Wong", zh:"張瑋桓" },
      { g:"M", en:"CHENG Siu Chi Nicholas", zh:"鄭肇致" },
      { g:"F", en:"Adithya Patali KARUNARATNE", zh:"李芬" },
      { g:"M", en:"TAM Sin Hang", zh:"譚善恆" },
      { g:"F", en:"LAI Ching Laam", zh:"黎清嵐" },
      { g:"M", en:"Kairan Creer THOMPSON", zh:"朱鍇泓" },
      { g:"F", en:"LIU Kallista", zh:"劉芷淇" },
      { g:"M", en:"WONG Chak Lam Coleman", zh:"黃澤林" },
      { g:"F", en:"SHEK Cheuk Ying", zh:"石卓盈" },
      { g:"M", en:"WONG Tsz Fu", zh:"王子夫" },
      { g:"F", en:"WONG Hong Yi", zh:"王康怡" },
    ]
  },
  triathlon: {
    label: "Triathlon 三項鐵人",
    athletes: [
      { g:"M", en:"Oscar Louis COGGINS", zh:"奧斯卡" },
      { g:"F", en:"Bailee Briana BROWN", zh:"彭詩雅" },
      { g:"M", en:"Robin Bent Edvin Thomas ELG", zh:"羅競賓" },
      { g:"F", en:"Cade Cameron WRIGHT", zh:"韋祺" },
      { g:"M", en:"WONG Tsz To", zh:"黃子圖" },
      { g:"F", en:"Tallulah Taye WRIGHT", zh:"韋禔" },
    ]
  },
  volleyball_beach: {
    label: "Volleyball-Beach 排球-沙灘",
    athletes: [
      { g:"M", en:"CHONG Kei Loi", zh:"莊紀來" },
      { g:"F", en:"TSANG Ngok Ling", zh:"曾岳羚" },
      { g:"M", en:"LEE Cheuk Hei", zh:"李卓曦" },
      { g:"F", en:"TO Wing Man", zh:"杜詠雯" },
      { g:"M", en:"LEE Lit Fung", zh:"李烈峰" },
      { g:"F", en:"TO Wing Tung", zh:"杜詠彤" },
      { g:"M", en:"WONG Pui Lam", zh:"王沛林" },
      { g:"F", en:"WONG Man Ching", zh:"黃雯靖" },
    ]
  },
  volleyball_indoor: {
    label: "Volleyball-Indoor 排球-室內",
    athletes: [
      { g:"M", en:"CHAN King Hoi", zh:"陳敬凱" },
      { g:"F", en:"CHEUNG Hiu Nok Michelle", zh:"張曉諾" },
      { g:"M", en:"CHENG Tsz Yui", zh:"鄭旨睿" },
      { g:"F", en:"CHIM Wing Lam", zh:"詹穎琳" },
      { g:"M", en:"CHEUNG Ngai Yiu", zh:"張藝耀" },
      { g:"F", en:"FONG Ka Yi", zh:"方家宜" },
      { g:"M", en:"CHIU Yin Laam", zh:"趙彥嵐" },
      { g:"F", en:"LEE Kit Sum", zh:"李潔心" },
      { g:"M", en:"KO Ching Kin", zh:"古靖堅" },
      { g:"F", en:"LEUNG Nga Yee", zh:"梁雅貽" },
      { g:"M", en:"KONG Cheuk Hin", zh:"江卓軒" },
      { g:"F", en:"SHUM Lam", zh:"沈嵐" },
      { g:"M", en:"LAM Sze Lok", zh:"林思樂" },
      { g:"F", en:"SUEN Yee Tung", zh:"孫綺彤" },
      { g:"M", en:"LAU Kin Ken", zh:"劉健勤" },
      { g:"F", en:"TANG Sum Yuen", zh:"鄧心弦" },
      { g:"M", en:"TAM Chun Ho Damian", zh:"譚竣顥" },
      { g:"F", en:"Halimah Zampaligre WILSON", zh:"彭琛怡" },
      { g:"M", en:"WAN Ka Nam", zh:"溫迦南" },
      { g:"F", en:"WONG Wan Wun", zh:"黃韻媛" },
      { g:"M", en:"WONG Cheuk Nam Samuel", zh:"黃卓楠" },
      { g:"F", en:"YIM Wing Ni", zh:"嚴泳妮" },
      { g:"M", en:"YUEN Sze Wai", zh:"袁思偉" },
      { g:"F", en:"YU Ying Chi", zh:"余映姿" },
    ]
  },
  weightlifting: {
    label: "Weightlifting 舉重",
    athletes: [
      { g:"M", en:"TUNG Matthew Jiayuan", zh:"童家元" },
      { g:"F", en:"CHENG Ching To", zh:"鄭凈淘" },
    ]
  },
  wrestling: {
    label: "Wrestling 摔跤",
    athletes: [
      { g:"M", en:"LI Wui Fung Vincent", zh:"李匯鋒" },
      { g:"M", en:"WONG Isaac Ching Shing", zh:"黃證誠" },
    ]
  },
  wushu: {
    label: "Wushu 武術",
    athletes: [
      { g:"M", en:"CHEN Jinsong", zh:"陳錦松" },
      { g:"F", en:"CHAN Tsz Ching", zh:"陳紫晴" },
      { g:"M", en:"CHEUNG Yat Lam", zh:"張溢霖" },
      { g:"F", en:"MOK Uen Ying Juanita", zh:"莫宛螢" },
      { g:"M", en:"HO Yin Ching", zh:"何彥政" },
      { g:"F", en:"SHAM Hui Yu Lydia", zh:"沈曉榆" },
      { g:"M", en:"LAU Chi Lung", zh:"劉子龍" },
      { g:"F", en:"YEUNG Michelle", zh:"楊子瑩" },
      { g:"M", en:"LEUNG Yu Hong", zh:"梁宇航" },
      { g:"M", en:"YEUNG Chung Hei", zh:"楊頌熹" },
    ]
  },
};

// Helper: get the roster (label + athlete list) for a disciplineKey, or null.
function getRoster(disciplineKey) {
  return disciplineKey && ROSTER[disciplineKey] ? ROSTER[disciplineKey] : null;
}

// Sports confirmed in the HKG delegation list that have NO matching row in the
// schedule sheet yet (mind sports / not yet scheduled in source data).
// Kept here so the UI can surface them as "pending schedule" rather than silently dropping them.
// disciplineKey is set where the delegation file confirms an athlete roster (Padel and
// Windsurfing both now have confirmed HKG athletes per the full roster file); the remaining
// entries are unconfirmed / no roster in the source file.
const HKG_UNSCHEDULED = [
  { sport:"帆船 - 滑浪風帆", disciplineKey:"sailing_windsurfing" },
  { sport:"板網球 (Padel)", disciplineKey:"padel" },
  { sport:"馬拉松游泳", disciplineKey:null },
  { sport:"橋牌", disciplineKey:null },
  { sport:"國際象棋", disciplineKey:null },
  { sport:"中國象棋", disciplineKey:null },
  { sport:"龍舟", disciplineKey:null },
  { sport:"滾軸運動 - 滾軸溜冰", disciplineKey:null },
];
